### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by byZeroOfficial** [joseywoermann/navnlos#157]
![](https://byzero.steals-code.tk/r/kq8ebvgyw9a.png)

**Comment by joseywoermann** [comment]
you saw nothing

**Comment by joseywoermann** [comment]
[Fixed](https://github.com/joseywoermann/navnlos/commit/3b6d3e1a53e3071f469e88046198b14228392379) on the dev branch, I'll push the fix to production with the next update.
