### ISSUE TITLE
Bug/incomplete sentence

### ISSUE THREAD

**Issue by joseywoermann** [joseywoermann/navnlos#21]
![Screenshot_2020-08-11-08-49-35-49_572064f74bd5f9fa804b05334aa4f912.jpg](https://user-images.githubusercontent.com/67111271/89866313-9bed4780-dbaf-11ea-8ba5-865b8871fa63.jpg)

**Comment by therealmistericraft** [comment]
I wanted to issue this thing too right now. Lol.

**Comment by joseywoermann** [comment]
Fixed
