### ISSUE TITLE
":one:" in poll command embed: TabError

### ISSUE THREAD

**Issue by therealmistericraft** [joseywoermann/navnlos#22]
The one emoji is not at the correct place: 
[Don't know how to put an image in here on mobile.](https://photos.app.goo.gl/ZdKFkejXsmBa3axR8)

**Comment by joseywoermann** [comment]
You see this? ![Screenshot_2020-08-11-09-41-08-46_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/67111271/89870871-ca225580-dbb6-11ea-8362-2b25d3fb4010.jpg)

**Comment by joseywoermann** [comment]
That tiny icon

**Comment by joseywoermann** [comment]
![IMG_20200811_094235.jpg](https://user-images.githubusercontent.com/67111271/89871007-02299880-dbb7-11ea-98f6-8f35593d8b4e.jpg)

**Comment by joseywoermann** [comment]
This bug only applies to mobile-phone-users.

**Comment by therealmistericraft** [comment]
This looks 180 degrees different on my mobile phone. There is no dark mode and only the ability to insert links...

**Comment by joseywoermann** [comment]
> This looks 180 degrees different on my mobile phone. There is no dark mode and only the ability to insert links...

Interesting...
