### ISSUE TITLE
$userinfo incomplete

### ISSUE THREAD

**Issue by therealmistericraft** [joseywoermann/navnlos#25]
With [_class_ discord.**Profile**](https://discordpy.readthedocs.io/en/latest/api.html#profile), you can add information like:

- Has the user a _Nitro_-Subscription?
    - Since when has he it?
- Is he a discord Staff or partner or bughunter or early supporter?
- Is he part of HypeSquad? Which houses is he in?
- Is he a discord employee?
- Which accounts are connected (like Twitch, Spotify, ...)

**Comment by joseywoermann** [comment]
Cancelled due to it being impossible.
