### ISSUE TITLE
Add translator

### ISSUE THREAD

**Issue by therealmistericraft** [joseywoermann/navnlos#29]
**Describe the solution you'd like**
Add a translator with google by passing the searched *source* word after the following link:
`https://translate.google.com/#view=home&op=translate&sl=auto&tl=de&text=`
It´s so configured, that it detects the language automatically.

**Additional context**
It could be called `$translate <WORD>`

**Comment by joseywoermann** [comment]
Unless Google gets its website-structure sorted out so that you can access it via web-scraping, this feature unfortunately won't be implemented.

**Comment by therealmistericraft** [comment]
Maybe you could use bing translate or linguee or pons or...

**Comment by joseywoermann** [comment]
@therealmistericraft I will probably take a look at some alternatives.

**Comment by joseywoermann** [comment]
this is more useful than I initially thought, and I will investigate this.

**Comment by joseywoermann** [comment]
[This](https://pypi.org/project/googletrans/) looks promising

**Comment by joseywoermann** [comment]
Hey, This feature will not be implemented into navnløs due to a change of plans concerning the future of the bot. I'll make an officiall announcement later today.
