### ISSUE TITLE
rework all features that deal with links

### ISSUE THREAD

**Issue by joseywoermann** [joseywoermann/navnlos#31]
instead of being lazy and just send links, get required information via web scraping

**Comment by peter-shoes** [comment]
@joseywoermann hey man, I can absolutely work on this if it's still open, can you just quickly explain to me what the issue is exactly? like you want a text scraping of a site with a given link?

**Comment by joseywoermann** [comment]
Hey @peter-shoes , first of all, thank you for asking!

Yes, I want to get the required information with web scraping.
Since I've already worked out how this is going to work and it doesn't involve a lot of commands ( only around 3), I would just quickly do this myself.

This issue was more like a reminder to myself to implement it.

**Comment by peter-shoes** [comment]
@joseywoermann funny enough, through a webscraping application called issuehub.io, it's pretty good at finding open issues and when i'm bored i just go on and look for projects to work on. all the best!

**Comment by joseywoermann** [comment]
@peter-shoes Stay safe!
