### ISSUE TITLE
$channeledit name deletes last message

### ISSUE THREAD

**Issue by therealmistericraft** [joseywoermann/navnlos#37]
If you do ``$channeledit name xy``, the message before gets deleted too.

https://user-images.githubusercontent.com/65766422/103171124-f1b64980-4849-11eb-8e85-d8374557f51c.mp4

**Comment by joseywoermann** [comment]
[Fixed](https://github.com/joseywoermann/navnlos/commit/8ea17d229ae3d1d5faef76fe98254b25b9064e0b)
