### ISSUE TITLE
At "$poll", there should not be a reply, because it looks awful

### ISSUE THREAD

**Issue by therealmistericraft** [joseywoermann/navnlos#60]
When you execute `§poll`, navnlos replies to your awful looking command. Instead, the command should be deleted and the poll occurs as before.
![image](https://user-images.githubusercontent.com/65766422/105176735-e93def80-5b25-11eb-9780-3475751b9d04.png)

**Comment by joseywoermann** [comment]
You're totally right there. I will implement this is V 2.2.0.

**Comment by joseywoermann** [comment]
Fixed in latest Alpha.
