### ISSUE TITLE
Give users in voicechats a role

### ISSUE THREAD

**Issue by therealmistericraft** [joseywoermann/navnlos#80]
It would be nice if you could mention persons in a voicechat. Therefore, you could give these persons a role and remove it if they disconnect, so that you can mention `@people in voicechat`.

**Comment by joseywoermann** [comment]
That's... useful.
I will look into this.

**Comment by joseywoermann** [comment]
@therealmistericraft The only problem with this is that _**every**_ member, will get this role, no matter what voice channel they are in.

**Comment by therealmistericraft** [comment]
On our small servers shouldnt be that a major problem.

**Comment by joseywoermann** [comment]
This feature has been implemented in the latest beta and will be released in version 2.2.0.
