### ISSUE TITLE
Update $invite

### ISSUE THREAD

**Issue by joseywoermann** [joseywoermann/navnlos#93]
This command should not give an invite to @therealmistericraft s server, but an bot invite

**Comment by joseywoermann** [comment]
done

**Comment by therealmistericraft** [comment]
What is about my server invitations? Is therefore another command?

**Comment by joseywoermann** [comment]
> What is about my server invitations? Is therefore another command?

oops

**Comment by joseywoermann** [comment]
> What is about my server invitations? Is therefore another command?

It makes way more sense if you would implement that feature into [your own bot](https://github.com/therealmistericraft/MisteriBot/).

I have **no plans** to re-add that feature to navnlos.

**Comment by joseywoermann** [comment]
> > What is about my server invitations? Is therefore another command?
> 
> It makes way more sense if you would implement that feature into [your own bot](https://github.com/therealmistericraft/MisteriBot/).
> 
> I have **no plans** to re-add that feature to navnlos.

@therealmistericraft Did you get that? I would like to have atleast _some_ feedback.

**Comment by therealmistericraft** [comment]
Yes, I am very sad about that, but I cannot change that.
