### ISSUE TITLE
Make "in voicechat"-feature toggleable

### ISSUE THREAD

**Issue by byZeroOfficial** [joseywoermann/navnlos#98]
## Commands idea
**$vc-role**
Enables a role that shows that someone is in a voicechannel.

## What do you think about this?
Whenever you type $vc-role, the role will be created or deleted, but by default I would leave it disabled.

**Comment by byZeroOfficial** [comment]
cuz just think about an owner, that just invited a bot, and the bot is creating a role. 
owner: ???
bot: !!!
![qu9iqY](https://user-images.githubusercontent.com/76685126/109013548-98d12900-76b3-11eb-9eeb-1e976fe08bc8.png)

**Comment by joseywoermann** [comment]
> cuz just think about an owner, that just invited a bot, and the bot is creating a role. 
> owner: ???
> bot: !!!
> ![qu9iqY](https://user-images.githubusercontent.com/76685126/109013548-98d12900-76b3-11eb-9eeb-1e976fe08bc8.png)
> 

_BetterDiscord_

**Comment by byZeroOfficial** [comment]
EHM

**Comment by joseywoermann** [comment]
> EHM

tse

**Comment by joseywoermann** [comment]
I have no idea if this is possible with the current hosting solution (Heroku), because the source gets re-build everyday so I can't really store configutation files.

I might make it that the bot "tries" to add the role, and if you don't want that feature, you just delete that role.

**Comment by joseywoermann** [comment]
#97

**Comment by byZeroOfficial** [comment]
okay
