### ISSUE TITLE
Command that moves all people in a Channel

### ISSUE THREAD

**Issue by byZeroOfficial** [joseywoermann/navnlos#99]
How about $moveus, or $moveall that would move all people into a specific voicechannel...
like for example:

$moveall `channelname`

**Comment by joseywoermann** [comment]
Noted!

**Comment by joseywoermann** [comment]
This feature will require a "re-authorisation" with a new OAuth2 scope, because the bot doesn't have the permissions to do so.

**Comment by byZeroOfficial** [comment]
Hmm... is there a solution for this?

**Comment by joseywoermann** [comment]
> Hmm... is there a solution for this?

Of course there is a solution, you would just have to kick to bot and add it again eith the new link.

**Comment by byZeroOfficial** [comment]
yea ok, i also got a second solution. 
_$moveall_ `old-channel` `new-channel`

**Comment by joseywoermann** [comment]
As I found very little use cases for such a feature, I instead added a command that moves a person into the channel you are currently in.
